# conda env create -f environment.yml
name: crispresso-env
channels:
- bioconda
- defaults
- conda-forge
dependencies:
- pip
- python
- bowtie2 
- samtools
- htslib
- ucsc-fatotwobit
- emboss
- pip:
    - -r requirements.txt
